### ISSUE TITLE
How to launch orenolisp?

### ISSUE THREAD

**Issue by minosniu** [illiichi/orenolisp#1]
Could you provide a more detailed step-by-step introduction? Thanks!

**Comment by maacl** [comment]
When trying to load luanch.clj I get the following error:

```
user=> (load-file "src/orenolisp/launch.clj")
Syntax error macroexpanding clojure.core/ns at (core.clj:1:1).
((require [llll.engine.engine :as en] [llll.sc.groups :as g] [llll.engine.variables :as v] [llll.sc.sound-control :as snd] [llll.sc.synth :as syn] [llll.macro.control] [mount.core :as mount])) - failed: Extra input spec: :clojure.core.specs.alpha/ns-form
```

**Comment by illiichi** [comment]
Thank you for your interst.

I fix version of internal library. Please pull the latest master, then could you try again?

I have no plans to make kind instructions so far. You can play sine sound by following instructions:

1. launch SuperCollider IDE and evaluate below SC codes:
```
s.options.maxLogins = 10;
s.boot;
```
2. evaluate all expressions in `launch.clj`
3. type `SPACE`, `s`, `TAB`, `(`, then `Alt-h`.

**Comment by maacl** [comment]
Great, this works. Thanks.
