### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by wildwestrom** [illiichi/orenolisp#4]
I have no idea how to run this project. I tried doing `lein run` and `lein uberjar` as I saw a `project.clj` file. It didn't start. What do I have to do?

**Comment by illiichi** [comment]
see https://github.com/illiichi/orenolisp/issues/1

**Comment by wildwestrom** [comment]
Ok, Will you add some instructions?

```md
## How to launch:
Dependencies:
- A java runtime that supports class file version 54.0 or greater (Java 10 or OpenJDK 11 supports this).
- Leiningen.
- Supercollider IDE

1. launch SuperCollider IDE and evaluate below SC codes:
  - `s.options.maxLogins = 10;`
  - `s.boot;`
2. In your terminal, run `lein repl`.
3. Then paste this: `(load-file "src/orenolisp/launch.clj")`
```
Tested on MacOS Mojave.
The IDE will launch, now I just have to get backspace to work.

**Comment by illiichi** [comment]
Thank you.
I added those instructions to README.md

**Comment by wildwestrom** [comment]
Awesomesauce!
